---
bar:
    height: 35
    hover: True
    name: bar
    offset: -4
    regions: 30
    colors:
        fg: base16.base07
        bg: base16.base00
    fonts:
        font1: "Envy Code R:pixelsize=22:style=Regular:antialias=true:autohint=true"
        font2: "Wuncon Siji:pixelsize=22:style=Regular:antialias=true:autohint=true"


blocks:
    left:
        static: "%{l}"

    left_corner:
        static: " "
        actions:
            1: bspc desktop -f last.occupied
            3: bspc desktop -f next.!occupied
            4: bspc desktop -f next.occupied
            5: bspc desktop -f prev.occupied
        colors:
            fg: yellow
            bg: blue

    bspwm:
        cmd: bspc subscribe report
        fmt: bspwm_fmt
        settings:
            show_monitor: False
            show_desktop_layout: True
            show_node_state: True
            show_node_flags: True

    xtitle:
        cmd: xtitle -s
        colors:
            fg: grey

    right:
        static: "%{r}"

    bitcoin:
        static: bitcoin

    weather:
        static: weather

    mpd:
        func: mpd
        colors:
            fg: yellow

    volume:
        static: volume

    cpu:
        static: cpu

    load:
        static: load

    mem:
        static: mem

    traffic:
        static: traffic

    clock:
        func: clock
        actions:
            1: xclock&
        colors:
            fg: bwhite
        settings:
            clockfmt: "%Y-%m-%d-%H:%M"

    right_corner:
        static: " "
        actions:
            1: nautilus.sh new&
            2: st ranger&
            3: nautilus.sh toggle&
        colors:
            fg: yellow
            bg: blue

colors:
    base16:
        base00: "#16130f"  # -----
        base01: "#2c2620"  # ----
        base02: "#433b32"  # ---
        base03: "#5a5047"  # --
        base04: "#8a8075"  # -
        base05: "#a39a90"  # +
        base06: "#beb6ae"  # ++
        base07: "#dbd6d1"  # +++
        base08: "#826d57"  # ++++
        base09: "#828257"  # +++++
        base0A: "#6d8257"
        base0B: "#57826d"
        base0C: "#576d82"
        base0D: "#6d5782"
        base0E: "#82576d"
        base0F: "#825757"

    terminal:
        black: "#16130f"     # base00, gray50
        red: "#cc475e"       # 350|65|80 red
        green: "#5ecc47"     # 110|65|80 green
        yellow: "#ccb647"    #  50|65|80 yellow
        blue: "#475ecc"      # 230|65|80 blue
        magenta: "#7447cc"   # 290|65|80 magenta
        cyan: "#47a0cc"      # 170|65|80 cyan
        white: "#beb6ae"     # base06, gray90
        grey: "#8C8A81"      # base01 black, bright
        bred: "#ff5975"      # 350|65|80 red
        bgreen: "#75ff59"    # 110|65|80 green
        byellow: "#ffe359"   #  50|65|80 yellow
        bblue: "#5975ff"     # 230|65|80 blue
        bmagenta: "#e359ff"  # 290|65|80 magenta
        bcyan: "#59c8ff"     # 170|65|80 cyan, light blue
        bwhite: "#f1f0ee"    # base07 white

...
