#!/usr/bin/python3

black="#16130f" # base00 gray 50
red="#cc475e" # 350 red
green="#5ecc47" # 110 green
yellow="#ccb647" # 50  yellow
blue="#475ecc" # 230 blue
magenta="#7447cc" # 290 magenta
cyan="#47a0cc" # 170 cyan
white="#beb6ae" # base06 gray 90
grey="#8C8A81" # base01 black, bright
bred="#ff5975" # 350 red
bgreen="#75ff59" # 110 green
byellow="#ffe359" # 50 yellow
bblue="#5975ff" # 230 blue
bmagenta="#e359ff" # 290 magenta
bcyan="#59c8ff" # 170 cyan, light blue
bwhite="#f1f0ee" # base07 white
